import React, { Suspense, useState } from "react";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";
import CoursesTabs from "../Tabs/CoursesTabs";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/templates/Layout";
import Testimonials from "../components/TestimonialsSections/Testimonials";
import dynamic from "next/dynamic";
import ChooseUs from "../components/sections/ChooseUs";
import Provide from "../components/sections/Provide";
import WhoWeAreSection from "../components/sections/WhoWeAreSection";
const InfoCardSection = dynamic(
  () => import("../components/InfoCard/InfoCardSection"),
  {
    suspense: true,
  }
);

export default function Home() {
  const [Images, setImages] = useState([
    {
      image:
        "https://images.unsplash.com/photo-1509062522246-3755977927d7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8ZWR1Y2F0aW9ufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=100",
    },
    {
      image:
        "https://images.unsplash.com/photo-1580582932707-520aed937b7b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGVkdWNhdGlvbnxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=100",
    },
  ]);
  const settings = {
    dots: true,
    fade: true,
    infinite: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    speed: 800,
    autoplaySpeed: 5000,
    cssEase: "linear",
    pauseOnHover: false,
  };

  return (
    <div>
      <Head>
        <title>HUB IT PVT. LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className=" w-full overflow-clip ">
          <Slider {...settings}>
            {Images.map((val, i) => {
              return (
                <div key={i} className="relative h-138 w-full">
                  <Image
                    src={val.image}
                    alt="images"
                    quality={75}
                    placeholder="blur"
                    blurDataURL={val.image}
                    sizes={"100vw"}
                    layout="fill"
                    objectFit="cover"
                    objectPosition="top"
                  />
                </div>
              );
            })}
          </Slider>
        </div>
        <div className="w-11/12 mx-auto">
          <Suspense fallback={<div className="animate-pulse">Loading</div>}>
            <div className="my-24">
              <InfoCardSection />
            </div>
          </Suspense>
          <div className="container mx-auto px-4 lg:px-8 my-16">
            <CoursesTabs />
          </div>
          <WhoWeAreSection />
          <ChooseUs />
          <Provide />
        </div>
        <Testimonials />
      </Layout>
    </div>
  );
}
